name: Notificacion CI

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificacion a ntfy
        run: |
          curl -H "Title: Nuevo push a main" \
               -H "Priority: high" \
               -d "Se subio nuevo codigo al repositorio " \
               https://ntfy.sh/devops-itla
